services:
  java:
    image: java_image
    build: /home/ubuntu/java
    container_name: java_container
    environment:
    - dbhost=shiv.cyxq3nw89gci.ap-south-1.rds.amazonaws.com
    - database=shiv
    - dbuser=shiv
    - dbpassword=shiv12345
    deploy:
        resources:
            limits:
              cpus: 0.50
              memory: 512M
            reservations:
              cpus: 0.25
              memory: 128M
    ports:
    - 8080:8080
